[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastembed>=0.7.1",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "qdrant-client[fastembed]>=1.14.2",
]
